// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e160b4e6-0ae9-4f9c-aac8-5a4dde6a04df";

const char SSID[]        = SECRET_SSID;
const char PASS[]        = SECRET_OPTIONAL_PASS;
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;

void onPressureChange();
void onHumidityChange();
void onTempertatureChange();

float pressure;
int humidity;
int tempertature;

void initProperties(){
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pressure, READWRITE, ON_CHANGE, onPressureChange);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(tempertature, READWRITE, ON_CHANGE, onTempertatureChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);